CREATE DATABASE IF NOT EXISTS poker_game CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE poker_game;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  chips INT NOT NULL DEFAULT 1000,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS hands (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  winner_name VARCHAR(100),
  pot INT NOT NULL DEFAULT 0,
  result_text VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
